import { useEffect, useState } from 'react'
import { useForm, useFieldArray } from 'react-hook-form'
import { useNavigate, useParams } from 'react-router-dom'
import { Plus, Trash2, Sparkles, Wand2 } from 'lucide-react'
import { useToast } from '../../context/ToastContext.jsx'
import api from '../../services/api.js'

export default function JobForm() {
  const { id } = useParams()
  const isEdit = Boolean(id)
  const navigate = useNavigate()
  const { showToast } = useToast()
  const [loading, setLoading] = useState(isEdit)
  const [error, setError] = useState('')
  const [generatingAi, setGeneratingAi] = useState(false)
  const [aiPrompt, setAiPrompt] = useState('')

  const { register, control, handleSubmit, reset, setValue } = useForm({
    defaultValues: {
      title: '',
      location: '',
      jobType: 'Full Time',
      workMode: 'Remote',
      experience: '',
      salary: '',
      description: '',
      skills: '',
      benefits: '',
      responsibilities: [{ value: '' }],
      requirements: [{ value: '' }],
      deadline: '',
    },
  })

  const resp = useFieldArray({ control, name: 'responsibilities' })
  const reqs = useFieldArray({ control, name: 'requirements' })

  useEffect(() => {
    if (!isEdit) return

    let mounted = true
    setLoading(true)

    api.get(`/jobs/${id}`)
      .then(({ data }) => {
        if (!mounted) return
        const job = data.job
        reset({
          title: job.title,
          location: job.location,
          jobType: job.jobType,
          workMode: job.workMode,
          experience: job.experience,
          salary: job.salary,
          description: job.description,
          skills: (job.skills || []).join(', '),
          benefits: (job.benefits || []).join(', '),
          responsibilities: (job.responsibilities || []).map((value) => ({ value })),
          requirements: (job.requirements || []).map((value) => ({ value })),
          deadline: job.deadline ? new Date(job.deadline).toISOString().slice(0, 10) : '',
        })
      })
      .catch(() => {
        if (mounted) setError('Unable to load job details.')
      })
      .finally(() => {
        if (mounted) setLoading(false)
      })

    return () => {
      mounted = false
    }
  }, [id, isEdit, reset])

  async function handleGenerateWithAi() {
    if (!aiPrompt.trim()) {
      showToast('Please enter a role title or description idea for AI generation.', 'danger')
      return
    }

    setGeneratingAi(true)
    try {
      const { data } = await api.post('/ai/generate-job-description', {
        prompt: aiPrompt,
        roleTitle: aiPrompt,
      })

      if (data.job) {
        const job = data.job
        if (job.title) setValue('title', job.title)
        if (job.description) setValue('description', job.description)
        if (job.skills?.length) setValue('skills', Array.isArray(job.skills) ? job.skills.join(', ') : job.skills)
        if (job.experience) setValue('experience', job.experience)
        if (job.jobType) setValue('jobType', job.jobType)
        if (job.workMode) setValue('workMode', job.workMode)
        if (job.salary) setValue('salary', job.salary)
        if (job.benefits) setValue('benefits', job.benefits)

        if (Array.isArray(job.responsibilities) && job.responsibilities.length) {
          setValue('responsibilities', job.responsibilities.map((r) => ({ value: r })))
        }
        if (Array.isArray(job.requirements) && job.requirements.length) {
          setValue('requirements', job.requirements.map((r) => ({ value: r })))
        }

        showToast('Job posting details generated by AI! Review and submit.', 'success')
      }
    } catch (err) {
      showToast(err.message || 'AI job generation failed.', 'danger')
    } finally {
      setGeneratingAi(false)
    }
  }

  async function onSubmit(formValues) {
    setError('')

    try {
      const payload = {
        title: formValues.title,
        location: formValues.location || 'Remote',
        jobType: formValues.jobType,
        workMode: formValues.workMode,
        experience: formValues.experience,
        salary: formValues.salary,
        description: formValues.description,
        skills: formValues.skills
          .split(',')
          .map((skill) => skill.trim())
          .filter(Boolean),
        benefits: formValues.benefits
          .split(',')
          .map((benefit) => benefit.trim())
          .filter(Boolean),
        deadline: formValues.deadline,
        responsibilities: formValues.responsibilities.map((item) => item.value).filter(Boolean),
        requirements: formValues.requirements.map((item) => item.value).filter(Boolean),
      }

      if (isEdit) {
        await api.put(`/jobs/${id}`, payload)
        showToast('Job updated successfully.', 'success')
      } else {
        await api.post('/jobs', payload)
        showToast('Job posted successfully.', 'success')
      }
      navigate('/recruiter/dashboard/jobs')
    } catch (err) {
      setError(err.message || 'Unable to save the job posting.')
    }
  }

  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
        <div>
          <h2 className="font-display text-xl font-bold text-ink">{isEdit ? 'Edit Job Posting' : 'Post a New Job'}</h2>
          <p className="mt-0.5 text-xs text-ink-soft">Create structured, high-attraction job listings for qualified candidates.</p>
        </div>
      </div>

      {/* 1-Click AI Job Posting Generator Box */}
      {!isEdit && (
        <div className="rounded-xl border border-signal/30 bg-gradient-to-r from-signal/15 via-white to-paper p-5 mb-6 shadow-xs">
          <div className="flex items-center gap-2.5 mb-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-ink text-signal">
              <Sparkles size={16} />
            </div>
            <div>
              <h3 className="font-display text-sm font-bold text-ink">1-Click AI Job Description Generator</h3>
              <p className="text-xs text-ink-soft">Enter a job title or prompt and Gemini will auto-generate requirements, duties, skills, & perks.</p>
            </div>
          </div>

          <div className="mt-3 flex flex-wrap gap-2">
            <input
              type="text"
              placeholder="e.g. Senior Full Stack Engineer (React + Node), UI/UX Designer, DevOps Cloud Architect"
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), handleGenerateWithAi())}
              className="input-field flex-1 text-xs"
            />
            <button
              type="button"
              onClick={handleGenerateWithAi}
              disabled={generatingAi || !aiPrompt.trim()}
              className="btn-primary text-xs flex items-center gap-1.5 shrink-0"
            >
              <Wand2 size={14} className={generatingAi ? 'animate-spin' : ''} />
              {generatingAi ? 'Generating Job Post…' : 'Generate with AI'}
            </button>
          </div>
        </div>
      )}

      {error && <div className="mb-4 rounded-md border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger">{error}</div>}

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-5 rounded-xl border border-ink/10 bg-white p-6 shadow-sm">
        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Job Title *</label>
            <input {...register('title', { required: true })} placeholder="e.g. Senior Frontend Engineer" className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Location *</label>
            <input {...register('location', { required: true })} placeholder="e.g. Bengaluru, Remote, San Francisco" className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Job Type</label>
            <select {...register('jobType')} className="input-field">
              {['Full Time', 'Part Time', 'Internship', 'Contract'].map((t) => <option key={t}>{t}</option>)}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Work Mode</label>
            <select {...register('workMode')} className="input-field">
              {['Remote', 'Hybrid', 'On-site'].map((m) => <option key={m}>{m}</option>)}
            </select>
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Experience Level</label>
            <input {...register('experience')} placeholder="e.g. 2-4 yrs" className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Salary Range</label>
            <input {...register('salary')} placeholder="e.g. ₹12L - ₹20L / year or $95,000 - $130,000" className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Key Skills (Comma Separated)</label>
            <input {...register('skills')} placeholder="React, TypeScript, Node.js, GraphQL" className="input-field" />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Application Deadline</label>
            <input {...register('deadline')} type="date" className="input-field" />
          </div>
        </div>

        <div>
          <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Job Overview & Description *</label>
          <textarea {...register('description', { required: true })} rows={4} placeholder="Describe the role responsibilities and mission..." className="input-field" />
        </div>

        <div>
          <label className="block text-xs font-semibold uppercase tracking-wider text-ink-soft mb-1">Benefits & Perks</label>
          <textarea {...register('benefits')} rows={2} placeholder="Health insurance, Remote stipend, Annual learning budget, ESOPs..." className="input-field" />
        </div>

        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-xs font-semibold uppercase tracking-wider text-ink-soft">Core Responsibilities</label>
            <button type="button" onClick={() => resp.append({ value: '' })} className="btn-ghost text-xs flex items-center gap-1"><Plus size={13} /> Add Item</button>
          </div>
          {resp.fields.map((f, i) => (
            <div key={f.id} className="mt-2 flex gap-2">
              <input {...register(`responsibilities.${i}.value`)} className="input-field text-xs" placeholder={`Responsibility ${i + 1}`} />
              <button type="button" onClick={() => resp.remove(i)} className="text-ink-soft hover:text-danger p-2"><Trash2 size={15} /></button>
            </div>
          ))}
        </div>

        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-xs font-semibold uppercase tracking-wider text-ink-soft">Key Requirements</label>
            <button type="button" onClick={() => reqs.append({ value: '' })} className="btn-ghost text-xs flex items-center gap-1"><Plus size={13} /> Add Item</button>
          </div>
          {reqs.fields.map((f, i) => (
            <div key={f.id} className="mt-2 flex gap-2">
              <input {...register(`requirements.${i}.value`)} className="input-field text-xs" placeholder={`Requirement ${i + 1}`} />
              <button type="button" onClick={() => reqs.remove(i)} className="text-ink-soft hover:text-danger p-2"><Trash2 size={15} /></button>
            </div>
          ))}
        </div>

        <div className="flex gap-3 pt-4 border-t border-ink/10">
          <button type="submit" disabled={loading} className="btn-primary flex items-center gap-2">{isEdit ? 'Save Changes' : 'Publish Job Posting'}</button>
          <button type="button" onClick={() => navigate('/recruiter/dashboard/jobs')} className="btn-secondary">Cancel</button>
        </div>
      </form>
    </div>
  )
}
